name: Dalfox Scan

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL to scan with Dalfox'
        required: true
        default: 'https://example.com'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    
    - name: Install Dalfox
      run: |
        go install github.com/hahwul/dalfox/v2@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Run Dalfox scan
      run: |
        dalfox url ${{ github.event.inputs.target_url }}
